repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: python -m mypy backend
        language: system
        pass_filenames: false
      - id: eslint
        name: eslint
        entry: npx eslint .
        language: system
        pass_filenames: false
      - id: prettier
        name: prettier
        entry: npx prettier --write "frontend/**/*.{js,html,css,ts}" "tests/frontend/*.{js,ts}"
        language: system
        pass_filenames: false
      - id: node-check
        name: node-check
        entry: npx vue-tsc --noEmit
        language: system
        pass_filenames: false
