/**
 * lucide 图标按需注册表。
 * 只打包本项目模板中实际使用的 45 个图标，避免全量 icons 导入导致 chunk >500KB。
 *
 * 使用方式：
 * ```ts
 * import { createIcons } from 'lucide';
 * import { UI_ICONS } from '@/modules/lucideIcons';
 * createIcons({ icons: UI_ICONS, attrs: { width: 16, height: 16 } });
 * ```
 *
 * createIcons 内部用 toPascalCase(iconName) 取 icons[PascalCase]，
 * 因此键必须为 PascalCase（与对象简写关键字一致）。
 */
import {
  Activity,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Bell,
  BellOff,
  BellPlus,
  BellRing,
  CalendarClock,
  ChartNoAxesCombined,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ClipboardPenLine,
  ClipboardPlus,
  CloudUpload,
  Database,
  Download,
  Gem,
  Grid3x3,
  Info,
  LayoutDashboard,
  Lightbulb,
  LoaderCircle,
  MoreHorizontal,
  Play,
  Plus,
  Radar,
  RefreshCw,
  Save,
  Scale,
  ScanSearch,
  Search,
  SearchX,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  StarOff,
  TrendingUp,
  TriangleAlert,
  UserRound,
  Wrench,
  X,
  Layers,
  Zap,
} from 'lucide';

export const UI_ICONS = {
  Activity,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Bell,
  BellOff,
  BellPlus,
  BellRing,
  CalendarClock,
  ChartNoAxesCombined,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ClipboardPenLine,
  ClipboardPlus,
  CloudUpload,
  Database,
  Download,
  Gem,
  Grid3x3,
  Info,
  LayoutDashboard,
  Lightbulb,
  LoaderCircle,
  MoreHorizontal,
  Play,
  Plus,
  Radar,
  RefreshCw,
  Save,
  Scale,
  ScanSearch,
  Search,
  SearchX,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  StarOff,
  TrendingUp,
  TriangleAlert,
  UserRound,
  Wrench,
  X,
  Layers,
  Zap,
};
