"""baseline schema

Revision ID: c1a08e78583e
Revises:
Create Date: 2026-08-30 22:36:00.249442

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1a08e78583e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("message", sa.String(length=2000), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_created_at"), "alerts", ["created_at"], unique=False)
    op.create_index(op.f("ix_alerts_read"), "alerts", ["read"], unique=False)
    op.create_index(op.f("ix_alerts_workspace_id"), "alerts", ["workspace_id"], unique=False)
    op.create_table(
        "grid_backtests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.String(length=96), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("trade_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_grid_backtests_code"), "grid_backtests", ["code"], unique=False)
    op.create_index(op.f("ix_grid_backtests_created_at"), "grid_backtests", ["created_at"], unique=False)
    op.create_index(op.f("ix_grid_backtests_strategy_id"), "grid_backtests", ["strategy_id"], unique=False)
    op.create_index(op.f("ix_grid_backtests_workspace_id"), "grid_backtests", ["workspace_id"], unique=False)
    op.create_table(
        "grid_strategies",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("lower", sa.Float(), nullable=False),
        sa.Column("upper", sa.Float(), nullable=False),
        sa.Column("grid_count", sa.Integer(), nullable=False),
        sa.Column("capital", sa.Float(), nullable=False),
        sa.Column("fee_bps", sa.Float(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("lookback", sa.Integer(), nullable=False),
        sa.Column("settlement_days", sa.Integer(), nullable=False),
        sa.Column("slippage_bps", sa.Float(), nullable=False),
        sa.Column("schedule", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_backtest_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_metrics", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_grid_strategies_code"), "grid_strategies", ["code"], unique=False)
    op.create_index(op.f("ix_grid_strategies_workspace_id"), "grid_strategies", ["workspace_id"], unique=False)
    op.create_table(
        "market_bars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("trade_date", sa.String(length=16), nullable=False),
        sa.Column("adjustment", sa.String(length=16), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", "trade_date", "adjustment", name="uq_market_bars_code_date_adjustment"),
    )
    op.create_index(op.f("ix_market_bars_code"), "market_bars", ["code"], unique=False)
    op.create_index(op.f("ix_market_bars_trade_date"), "market_bars", ["trade_date"], unique=False)
    op.create_table(
        "strategies",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("strategy_type", sa.String(length=24), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("capital", sa.Float(), nullable=False),
        sa.Column("fee_bps", sa.Float(), nullable=False),
        sa.Column("schedule", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_backtest_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latest_metrics", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_strategies_code"), "strategies", ["code"], unique=False)
    op.create_index(op.f("ix_strategies_strategy_type"), "strategies", ["strategy_type"], unique=False)
    op.create_index(op.f("ix_strategies_workspace_id"), "strategies", ["workspace_id"], unique=False)
    op.create_table(
        "strategy_backtests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sa.String(length=96), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("strategy_type", sa.String(length=24), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("trade_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_strategy_backtests_code"), "strategy_backtests", ["code"], unique=False)
    op.create_index(op.f("ix_strategy_backtests_created_at"), "strategy_backtests", ["created_at"], unique=False)
    op.create_index(op.f("ix_strategy_backtests_strategy_id"), "strategy_backtests", ["strategy_id"], unique=False)
    op.create_index(op.f("ix_strategy_backtests_strategy_type"), "strategy_backtests", ["strategy_type"], unique=False)
    op.create_index(op.f("ix_strategy_backtests_workspace_id"), "strategy_backtests", ["workspace_id"], unique=False)
    op.create_table(
        "trade_plans",
        sa.Column("id", sa.String(length=96), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("entry", sa.Float(), nullable=False),
        sa.Column("stop", sa.Float(), nullable=False),
        sa.Column("target", sa.Float(), nullable=False),
        sa.Column("capital", sa.Float(), nullable=False),
        sa.Column("position", sa.Float(), nullable=False),
        sa.Column("validity", sa.String(length=32), nullable=False),
        sa.Column("note", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("triggered", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trade_plans_code"), "trade_plans", ["code"], unique=False)
    op.create_index(op.f("ix_trade_plans_status"), "trade_plans", ["status"], unique=False)
    op.create_index(op.f("ix_trade_plans_workspace_id"), "trade_plans", ["workspace_id"], unique=False)
    op.create_table(
        "watchlist_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "code", name="uq_watchlist_workspace_code"),
    )
    op.create_index(op.f("ix_watchlist_items_code"), "watchlist_items", ["code"], unique=False)
    op.create_index(op.f("ix_watchlist_items_workspace_id"), "watchlist_items", ["workspace_id"], unique=False)
    op.create_table(
        "workspace_settings",
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("workspace_id"),
    )
    op.create_table(
        "workspace_state",
        sa.Column("workspace_id", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("workspace_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workspace_state")
    op.drop_table("workspace_settings")
    op.drop_index(op.f("ix_watchlist_items_workspace_id"), table_name="watchlist_items")
    op.drop_index(op.f("ix_watchlist_items_code"), table_name="watchlist_items")
    op.drop_table("watchlist_items")
    op.drop_index(op.f("ix_trade_plans_workspace_id"), table_name="trade_plans")
    op.drop_index(op.f("ix_trade_plans_status"), table_name="trade_plans")
    op.drop_index(op.f("ix_trade_plans_code"), table_name="trade_plans")
    op.drop_table("trade_plans")
    op.drop_index(op.f("ix_strategy_backtests_workspace_id"), table_name="strategy_backtests")
    op.drop_index(op.f("ix_strategy_backtests_strategy_type"), table_name="strategy_backtests")
    op.drop_index(op.f("ix_strategy_backtests_strategy_id"), table_name="strategy_backtests")
    op.drop_index(op.f("ix_strategy_backtests_created_at"), table_name="strategy_backtests")
    op.drop_index(op.f("ix_strategy_backtests_code"), table_name="strategy_backtests")
    op.drop_table("strategy_backtests")
    op.drop_index(op.f("ix_strategies_workspace_id"), table_name="strategies")
    op.drop_index(op.f("ix_strategies_strategy_type"), table_name="strategies")
    op.drop_index(op.f("ix_strategies_code"), table_name="strategies")
    op.drop_table("strategies")
    op.drop_index(op.f("ix_market_bars_trade_date"), table_name="market_bars")
    op.drop_index(op.f("ix_market_bars_code"), table_name="market_bars")
    op.drop_table("market_bars")
    op.drop_index(op.f("ix_grid_strategies_workspace_id"), table_name="grid_strategies")
    op.drop_index(op.f("ix_grid_strategies_code"), table_name="grid_strategies")
    op.drop_table("grid_strategies")
    op.drop_index(op.f("ix_grid_backtests_workspace_id"), table_name="grid_backtests")
    op.drop_index(op.f("ix_grid_backtests_strategy_id"), table_name="grid_backtests")
    op.drop_index(op.f("ix_grid_backtests_created_at"), table_name="grid_backtests")
    op.drop_index(op.f("ix_grid_backtests_code"), table_name="grid_backtests")
    op.drop_table("grid_backtests")
    op.drop_index(op.f("ix_alerts_workspace_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_read"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_created_at"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
